# Dealing with missing data

In [1]:
import pandas as pd
import numpy as np

In [2]:
# Create a DataFrame with some NaN values
data = {
    "A": [1.0, 5.0, 10.0],
    "B": [2.0, 6.0, 11.0],
    "C": [3.0, np.nan, 12.0],
    "D": [4.0, 8.0, np.nan],
}

In [3]:
# Create the DataFrame
df = pd.DataFrame(data)
display(df)

      A     B     C    D
0   1.0   2.0   3.0  4.0
1   5.0   6.0   NaN  8.0
2  10.0  11.0  12.0  NaN

In [6]:
# Check for missing values in each column
display(df.isnull())
display(df.isnull().sum())

       A      B      C      D
0  False  False  False  False
1  False  False   True  False
2  False  False  False   True

A    0
B    0
C    1
D    1
dtype: int64

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      float64
 1   B       3 non-null      float64
 2   C       2 non-null      float64
 3   D       2 non-null      float64
dtypes: float64(4)
memory usage: 224.0 bytes

## Eliminating samples or features with missing values

In [8]:
# Drop rows with any missing values
df.dropna()

     A    B    C    D
0  1.0  2.0  3.0  4.0

In [10]:
# Drop columns with any missing values
df.dropna(axis=1)

      A     B
0   1.0   2.0
1   5.0   6.0
2  10.0  11.0

In [15]:
# Introduce a NaN value for demonstration
df.loc[3, :] = np.nan
display(df)

      A     B     C    D
0   1.0   2.0   3.0  4.0
1   5.0   6.0   NaN  8.0
2  10.0  11.0  12.0  NaN
3   NaN   NaN   NaN  NaN

In [16]:
# Drop rows where all elements are NaN
df.dropna(how="all")

      A     B     C    D
0   1.0   2.0   3.0  4.0
1   5.0   6.0   NaN  8.0
2  10.0  11.0  12.0  NaN

In [18]:
# Drop rows with less than 4 non-NaN values
df.dropna(thresh=4)

     A    B    C    D
0  1.0  2.0  3.0  4.0

In [19]:
# Drop rows with missing values in column 'C'
df.dropna(subset=["C"])

      A     B     C    D
0   1.0   2.0   3.0  4.0
2  10.0  11.0  12.0  NaN

# Filling in missing data

In [20]:
# Display the final DataFrame
display(df)

      A     B     C    D
0   1.0   2.0   3.0  4.0
1   5.0   6.0   NaN  8.0
2  10.0  11.0  12.0  NaN
3   NaN   NaN   NaN  NaN

In [21]:
# Fill missing values with 0
df.fillna(0)

      A     B     C    D
0   1.0   2.0   3.0  4.0
1   5.0   6.0   0.0  8.0
2  10.0  11.0  12.0  0.0
3   0.0   0.0   0.0  0.0

In [22]:
# Fill missing values with -1
df.fillna(-1)

      A     B     C    D
0   1.0   2.0   3.0  4.0
1   5.0   6.0  -1.0  8.0
2  10.0  11.0  12.0 -1.0
3  -1.0  -1.0  -1.0 -1.0

In [25]:
# Show mean of each column, ignoring NaN values
display(df.mean())
display(df.fillna(df.mean()))

A    5.333333
B    6.333333
C    7.500000
D    6.000000
dtype: float64

           A          B     C    D
0   1.000000   2.000000   3.0  4.0
1   5.000000   6.000000   7.5  8.0
2  10.000000  11.000000  12.0  6.0
3   5.333333   6.333333   7.5  6.0

In [ ]:
# Fill missing values with the mean of each column. This is called mean imputation.