## Handling Duplicated Data

In [1]:
import pandas as pd

## Primer

In [2]:
# Create a sample DataFrame with duplicated rows
df = pd.DataFrame(
    {
        "Name": ["John", "Rock", "Neil", "Tom", "John", "John"],
        "Rank": [1, 2, 3, 6, 1, 1],
        "Marks": [98, 59, 97, 99, 98, 98],
    }
)
display(df)

   Name  Rank  Marks
0  John     1     98
1  Rock     2     59
2  Neil     3     97
3   Tom     6     99
4  John     1     98
5  John     1     98

In [3]:
# Identify duplicated rows, keeping the first occurrence
df.duplicated(keep="first")

0    False
1    False
2    False
3    False
4     True
5     True
dtype: bool

In [4]:
# Identify duplicated rows, keeping the last occurrence
df.duplicated(keep="last")

0     True
1    False
2    False
3    False
4     True
5    False
dtype: bool

In [5]:
# Count total number of duplicated rows
df.duplicated().sum()

np.int64(2)

In [6]:
# Display duplicated rows
# Note: we use boolean indexing to filter the DataFrame. We will learn more about this in the next lesson.
df[df.duplicated()]

   Name  Rank  Marks
4  John     1     98
5  John     1     98

In [7]:
# Remove duplicated rows, keeping the first occurrence
df.drop_duplicates(keep="first")

   Name  Rank  Marks
0  John     1     98
1  Rock     2     59
2  Neil     3     97
3   Tom     6     99

In [8]:
# Remove duplicated rows, keeping the last occurrence
df.drop_duplicates(keep="last")

   Name  Rank  Marks
1  Rock     2     59
2  Neil     3     97
3   Tom     6     99
5  John     1     98

## Real Data

In [9]:
# Load the Adult dataset
adult = pd.read_csv("./data/adult.csv")

In [10]:
# Display the first few rows of the dataset
display(adult.head())

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
3,24,Private,369667,Some-college,10,Never-married,Other-service,Unmarried,White,Female,0,0,40,United-States,<=50K
4,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K

In [11]:
# Display dataset information
adult.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3246 entries, 0 to 3245
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   age              3246 non-null   int64
 1   workclass        3246 non-null   object
 2   fnlwgt           3246 non-null   int64
 3   education        3246 non-null   object
 4   educational-num  3246 non-null   int64
 5   marital-status   3246 non-null   object
 6   occupation       3246 non-null   object
 7   relationship     3246 non-null   object
 8   race             3246 non-null   object
 9   gender           3246 non-null   object
 10  capital-gain     3246 non-null   int64
 11  capital-loss     3246 non-null   int64
 12  hours-per-week   3246 non-null   int64
 13  native-country   3246 non-null   object
 14  income           3246 non-null   object
dtypes: int64(6), object(9)
memory usage: 380.5+ KB

In [15]:
print(adult.isnull().sum())

age                0
workclass          0
fnlwgt             0
education          0
educational-num    0
marital-status     0
occupation         0
relationship       0
race               0
gender             0
capital-gain       0
capital-loss       0
hours-per-week     0
native-country     0
income             0
dtype: int64

In [12]:
# Identify duplicated rows in the Adult dataset
adult.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
3241    False
3242    False
3243    False
3244    False
3245    False
Length: 3246, dtype: bool

In [16]:
# Count total number of duplicated rows in the Adult dataset
print(adult.duplicated().sum())

9

In [14]:
# Display duplicated rows in the Adult dataset
adult[adult.duplicated()]

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
9,24,Private,369667,Some-college,10,Never-married,Other-service,Unmarried,White,Female,0,0,40,United-States,<=50K
27,45,Self-emp-not-inc,432824,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,7298,0,90,United-States,>50K
53,18,Private,54440,Some-college,10,Never-married,Other-service,Own-child,White,Male,0,0,20,United-States,<=50K
867,24,Private,194630,Bachelors,13,Never-married,Prof-specialty,Not-in-family,White,Male,0,0,35,United-States,<=50K
2528,48,Private,56071,Bachelors,13,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,>50K
2687,41,Private,319271,Some-college,10,Married-civ-spouse,Sales,Husband,White,Male,0,0,50,United-States,<=50K
2794,25,Private,199143,HS-grad,9,Divorced,Craft-repair,Own-child,White,Male,0,0,40,United-States,<=50K
2884,22,Private,333838,HS-grad,9,Never-married,Adm-clerical,Not-in-family,White,Male,0,0,40,United-States,<=50K
3076,44,Private,141131,12th,8,Divorced,Machine-op-inspct,Unmarried,Asian-Pac-Islander,Female,0,0,40,South,<=50K

In [17]:
# Remove duplicated rows, keeping the first occurrence
adult.drop_duplicates(keep="first")

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
3,24,Private,369667,Some-college,10,Never-married,Other-service,Unmarried,White,Female,0,0,40,United-States,<=50K
4,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3241,18,Private,161245,11th,7,Never-married,Other-service,Own-child,White,Male,0,0,8,United-States,<=50K
3242,32,Private,262024,HS-grad,9,Never-married,Other-service,Own-child,Black,Male,0,0,38,United-States,<=50K
3243,21,Private,287681,HS-grad,9,Never-married,Machine-op-inspct,Own-child,White,Male,0,0,40,Mexico,<=50K
3244,27,Private,303601,12th,8,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,40,United-States,<=50K
3245,58,?,365410,Some-college,10,Separated,?,Other-relative,White,Female,0,0,99,United-States,<=50K

In [19]:
# Display the shape of the original and cleaned datasets
print(f"The shape of the original dataset: {adult.shape}")
print("-"*50)
clean_adult = adult.drop_duplicates(keep="first")
print(f"The shape of the cleaned dataset: {clean_adult.shape}")

The shape of the original dataset: (3246, 15)
--------------------------------------------------
The shape of the cleaned dataset: (3237, 15)

In [21]:
# Remove duplicates based on specific columns: "age" and "workclass"
adult.drop_duplicates(subset=["age", "workclass"])

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
3,24,Private,369667,Some-college,10,Never-married,Other-service,Unmarried,White,Female,0,0,40,United-States,<=50K
4,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2778,20,Self-emp-inc,154782,HS-grad,9,Never-married,Farming-fishing,Own-child,White,Male,0,0,20,United-States,<=50K
2820,63,Federal-gov,160473,HS-grad,9,Widowed,Adm-clerical,Not-in-family,White,Female,0,0,40,United-States,<=50K
2964,19,Without-pay,43627,HS-grad,9,Never-married,Other-service,Own-child,White,Male,0,0,10,United-States,<=50K
3145,66,Local-gov,154171,Some-college,10,Widowed,Machine-op-inspct,Not-in-family,White,Male,0,0,20,United-States,<=50K
3185,74,Without-pay,216001,7th-8th,4,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,20,United-States,<=50K