# Grouping

In [1]:
import pandas as pd

In [2]:
# Load the drinks dataset
drinks = pd.read_csv("./data/drinks.csv")
drinks.head()

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
0,Afghanistan,0,0,0,0.0,AS
1,Albania,89,132,54,4.9,EU
2,Algeria,25,0,14,0.7,AF
3,Andorra,245,138,312,12.4,EU
4,Angola,217,57,45,5.9,AF

In [3]:
# Inspecting data to see if there are any missing values. (Yes, there are)
drinks.isnull().sum()

country                          0
beer_servings                    0
spirit_servings                  0
wine_servings                    0
total_litres_of_pure_alcohol     0
continent                       23
dtype: int64

In [4]:
# Create a boolean filter for rows with any missing values
filt = drinks["continent"].isna()

drinks[filt]

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
5,Antigua & Barbuda,102,128,45,4.9,NaN
11,Bahamas,122,176,51,6.3,NaN
14,Barbados,143,173,36,6.3,NaN
17,Belize,263,114,8,6.8,NaN
32,Canada,240,122,100,8.2,NaN
41,Costa Rica,149,87,11,4.4,NaN
43,Cuba,93,137,5,4.2,NaN
50,Dominica,52,286,26,6.6,NaN
51,Dominican Republic,193,147,9,6.2,NaN
54,El Salvador,52,69,2,2.2,NaN
68,Grenada,199,438,28,11.9,NaN
69,Guatemala,53,69,2,2.2,NaN
73,Haiti,1,326,1,5.9,NaN
74,Honduras,69,98,2,3.0,NaN
84,Jamaica,82,97,9,3.4,NaN
109,Mexico,238,68,5,5.5,NaN
122,Nicaragua,78,118,1,3.5,NaN
130,Panama,285,104,18,7.2,NaN
143,St. Kitts & Nevis,194,205,32,7.7,NaN
144,St. Lucia,171,315,71,10.1,NaN
145,St. Vincent & the Grenadines,120,221,11,6.3,NaN
174,Trinidad & Tobago,197,156,7,6.4,NaN
184,USA,249,158,84,8.7,NaN

In [7]:
# Fill missing values in the "continent" column with "UNKNOWN"
drinks["continent"] = drinks["continent"].fillna("UNKNOWN")
drinks.isnull().sum()

country                         0
beer_servings                   0
spirit_servings                 0
wine_servings                   0
total_litres_of_pure_alcohol    0
continent                       0
dtype: int64

In [8]:
# Group the drinks DataFrame by the "continent" column
drinks_grouped = drinks.groupby(by="continent")

In [9]:
# Get the number of unique continents in the dataset
drinks_grouped.ngroups

6

In [10]:
# Get the number of rows in each group.
display(drinks_grouped.size())

# Another way to get the number of rows in each group.
# The aggregate function .count() counts only the non-null values from each column,
# whereas .size() simply returns the number of rows available in each group irrespective of presence or absence of values.
display(drinks_grouped.count())

continent
AF         53
AS         44
EU         45
OC         16
SA         12
UNKNOWN    23
dtype: int64

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol
continent,,,,,
AF,53,53,53,53,53
AS,44,44,44,44,44
EU,45,45,45,45,45
OC,16,16,16,16,16
SA,12,12,12,12,12
UNKNOWN,23,23,23,23,23

In [11]:
# Get the number of unique values in each column for each continent
drinks_grouped["beer_servings"].nunique()

continent
AF         43
AS         28
EU         41
OC         14
SA         12
UNKNOWN    22
Name: beer_servings, dtype: int64

In [13]:
# Sample a row from each group
display(drinks_grouped.first())

# Get the last row from each group
display(drinks_grouped.last())

# Get the second row from each group
display(drinks_grouped.nth(1))

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol
continent,,,,,
AF,Algeria,25,0,14,0.7
AS,Afghanistan,0,0,0,0.0
EU,Albania,89,132,54,4.9
OC,Australia,261,72,212,10.4
SA,Argentina,193,25,221,8.3
UNKNOWN,Antigua & Barbuda,102,128,45,4.9

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol
continent,,,,,
AF,Zimbabwe,64,18,4,4.7
AS,Yemen,6,0,0,0.1
EU,United Kingdom,219,126,195,10.4
OC,Vanuatu,21,18,11,0.9
SA,Venezuela,333,100,3,7.7
UNKNOWN,USA,249,158,84,8.7

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
3,Andorra,245,138,312,12.4,EU
4,Angola,217,57,45,5.9,AF
11,Bahamas,122,176,51,6.3,UNKNOWN
12,Bahrain,42,63,7,2.0,AS
20,Bolivia,167,41,8,3.8,SA
40,Cook Islands,0,254,74,5.9,OC

In [14]:
# Get the mean beer servings for each continent
drinks_grouped["beer_servings"].mean()

continent
AF          61.471698
AS          37.045455
EU         193.777778
OC          89.687500
SA         175.083333
UNKNOWN    145.434783
Name: beer_servings, dtype: float64

In [15]:
# Get the data for a specific group, e.g., Africa ("AF")
drinks_grouped.get_group("AF")

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
2,Algeria,25,0,14,0.7,AF
4,Angola,217,57,45,5.9,AF
18,Benin,34,4,13,1.1,AF
22,Botswana,173,35,35,5.4,AF
26,Burkina Faso,25,7,7,4.3,AF
27,Burundi,88,0,0,6.3,AF
28,Cote d'Ivoire,37,1,7,4.0,AF
29,Cabo Verde,144,56,16,4.0,AF
31,Cameroon,147,1,4,5.8,AF
33,Central African Republic,17,2,1,1.8,AF
34,Chad,15,1,1,0.4,AF
38,Comoros,1,3,1,0.1,AF
39,Congo,76,1,9,1.7,AF
47,DR Congo,32,3,1,2.3,AF
49,Djibouti,15,44,3,1.1,AF
53,Egypt,6,4,1,0.2,AF
55,Equatorial Guinea,92,0,233,5.8,AF
56,Eritrea,18,0,0,0.5,AF
58,Ethiopia,20,3,0,0.7,AF
62,Gabon,347,98,59,8.9,AF
63,Gambia,8,0,1,2.4,AF
66,Ghana,31,3,10,1.8,AF
70,Guinea,9,0,2,0.2,AF
71,Guinea-Bissau,28,31,21,2.5,AF
88,Kenya,58,22,2,1.8,AF
95,Lesotho,82,29,0,2.8,AF
96,Liberia,19,152,2,3.1,AF
97,Libya,0,0,0,0.0,AF
100,Madagascar,26,15,4,0.8,AF
101,Malawi,8,11,1,1.5,AF
104,Mali,5,1,1,0.6,AF
107,Mauritania,0,0,0,0.0,AF
108,Mauritius,98,31,18,2.6,AF
114,Morocco,12,6,10,0.5,AF
115,Mozambique,47,18,5,1.3,AF
117,Namibia,376,3,1,6.8,AF
123,Niger,3,2,1,0.1,AF
124,Nigeria,42,5,2,9.1,AF
142,Rwanda,43,2,0,6.8,AF
148,Sao Tome & Principe,56,38,140,4.2,AF
150,Senegal,9,1,7,0.3,AF
152,Seychelles,157,25,51,4.1,AF
153,Sierra Leone,25,3,2,6.7,AF
158,Somalia,0,0,0,0.0,AF
159,South Africa,225,76,81,8.2,AF
162,Sudan,8,13,0,1.7,AF
164,Swaziland,90,2,2,4.7,AF
172,Togo,36,2,19,1.3,AF
175,Tunisia,51,3,20,1.3,AF
179,Uganda,45,9,0,8.3,AF
183,Tanzania,36,6,1,5.7,AF
191,Zambia,32,19,4,2.5,AF
192,Zimbabwe,64,18,4,4.7,AF

In [16]:
# Get the data for an arbitrary group using the group keys
# Create a list of group names
group_list = list(drinks_grouped.groups.keys())

# Get the data for the first group in the list
drinks_grouped.get_group(group_list[0])

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
2,Algeria,25,0,14,0.7,AF
4,Angola,217,57,45,5.9,AF
18,Benin,34,4,13,1.1,AF
22,Botswana,173,35,35,5.4,AF
26,Burkina Faso,25,7,7,4.3,AF
27,Burundi,88,0,0,6.3,AF
28,Cote d'Ivoire,37,1,7,4.0,AF
29,Cabo Verde,144,56,16,4.0,AF
31,Cameroon,147,1,4,5.8,AF
33,Central African Republic,17,2,1,1.8,AF
34,Chad,15,1,1,0.4,AF
38,Comoros,1,3,1,0.1,AF
39,Congo,76,1,9,1.7,AF
47,DR Congo,32,3,1,2.3,AF
49,Djibouti,15,44,3,1.1,AF
53,Egypt,6,4,1,0.2,AF
55,Equatorial Guinea,92,0,233,5.8,AF
56,Eritrea,18,0,0,0.5,AF
58,Ethiopia,20,3,0,0.7,AF
62,Gabon,347,98,59,8.9,AF
63,Gambia,8,0,1,2.4,AF
66,Ghana,31,3,10,1.8,AF
70,Guinea,9,0,2,0.2,AF
71,Guinea-Bissau,28,31,21,2.5,AF
88,Kenya,58,22,2,1.8,AF
95,Lesotho,82,29,0,2.8,AF
96,Liberia,19,152,2,3.1,AF
97,Libya,0,0,0,0.0,AF
100,Madagascar,26,15,4,0.8,AF
101,Malawi,8,11,1,1.5,AF
104,Mali,5,1,1,0.6,AF
107,Mauritania,0,0,0,0.0,AF
108,Mauritius,98,31,18,2.6,AF
114,Morocco,12,6,10,0.5,AF
115,Mozambique,47,18,5,1.3,AF
117,Namibia,376,3,1,6.8,AF
123,Niger,3,2,1,0.1,AF
124,Nigeria,42,5,2,9.1,AF
142,Rwanda,43,2,0,6.8,AF
148,Sao Tome & Principe,56,38,140,4.2,AF
150,Senegal,9,1,7,0.3,AF
152,Seychelles,157,25,51,4.1,AF
153,Sierra Leone,25,3,2,6.7,AF
158,Somalia,0,0,0,0.0,AF
159,South Africa,225,76,81,8.2,AF
162,Sudan,8,13,0,1.7,AF
164,Swaziland,90,2,2,4.7,AF
172,Togo,36,2,19,1.3,AF
175,Tunisia,51,3,20,1.3,AF
179,Uganda,45,9,0,8.3,AF
183,Tanzania,36,6,1,5.7,AF
191,Zambia,32,19,4,2.5,AF
192,Zimbabwe,64,18,4,4.7,AF

In [20]:
# Iterate over each group and display the group name and first row of the group
for key, group in drinks_grouped:
    print(key)
    display(group.iloc[0])

AF

country                         Algeria
beer_servings                        25
spirit_servings                       0
wine_servings                        14
total_litres_of_pure_alcohol        0.7
continent                            AF
Name: 2, dtype: object

AS

country                         Afghanistan
beer_servings                             0
spirit_servings                           0
wine_servings                             0
total_litres_of_pure_alcohol            0.0
continent                                AS
Name: 0, dtype: object

EU

country                         Albania
beer_servings                        89
spirit_servings                     132
wine_servings                        54
total_litres_of_pure_alcohol        4.9
continent                            EU
Name: 1, dtype: object

OC

country                         Australia
beer_servings                         261
spirit_servings                        72
wine_servings                         212
total_litres_of_pure_alcohol         10.4
continent                              OC
Name: 8, dtype: object

SA

country                         Argentina
beer_servings                         193
spirit_servings                        25
wine_servings                         221
total_litres_of_pure_alcohol          8.3
continent                              SA
Name: 6, dtype: object

UNKNOWN

country                         Antigua & Barbuda
beer_servings                                 102
spirit_servings                               128
wine_servings                                  45
total_litres_of_pure_alcohol                  4.9
continent                                 UNKNOWN
Name: 5, dtype: object

In [22]:
# Iterate over each group and display the group name and first row of the group
for group in group_list:
    print(f"Group: {group}")
    display(drinks_grouped.get_group(group).iloc[0])

Group: AF

country                         Algeria
beer_servings                        25
spirit_servings                       0
wine_servings                        14
total_litres_of_pure_alcohol        0.7
continent                            AF
Name: 2, dtype: object

Group: AS

country                         Afghanistan
beer_servings                             0
spirit_servings                           0
wine_servings                             0
total_litres_of_pure_alcohol            0.0
continent                                AS
Name: 0, dtype: object

Group: EU

country                         Albania
beer_servings                        89
spirit_servings                     132
wine_servings                        54
total_litres_of_pure_alcohol        4.9
continent                            EU
Name: 1, dtype: object

Group: OC

country                         Australia
beer_servings                         261
spirit_servings                        72
wine_servings                         212
total_litres_of_pure_alcohol         10.4
continent                              OC
Name: 8, dtype: object

Group: SA

country                         Argentina
beer_servings                         193
spirit_servings                        25
wine_servings                         221
total_litres_of_pure_alcohol          8.3
continent                              SA
Name: 6, dtype: object

Group: UNKNOWN

country                         Antigua & Barbuda
beer_servings                                 102
spirit_servings                               128
wine_servings                                  45
total_litres_of_pure_alcohol                  4.9
continent                                 UNKNOWN
Name: 5, dtype: object

In [23]:
# Get the mean beer and wine servings for each continent
drinks_grouped[["beer_servings", "wine_servings"]].mean()

           beer_servings  wine_servings
continent
AF             61.471698      16.264151
AS             37.045455       9.068182
EU            193.777778     142.222222
OC             89.687500      35.625000
SA            175.083333      62.416667
UNKNOWN       145.434783      24.521739

In [24]:
# Get descriptive statistics for wine servings for each continent
drinks_grouped["wine_servings"].describe()

           count        mean        std  min   25%    50%     75%    max
continent
AF          53.0   16.264151  38.846419  0.0   1.0    2.0   13.00  233.0
AS          44.0    9.068182  21.667034  0.0   0.0    1.0    8.00  123.0
EU          45.0  142.222222  97.421738  0.0  59.0  128.0  195.00  370.0
OC          16.0   35.625000  64.555790  0.0   1.0    8.5   23.25  212.0
SA          12.0   62.416667  88.620189  1.0   3.0   12.0   98.50  221.0
UNKNOWN     23.0   24.521739  28.266378  1.0   5.0   11.0   34.00  100.0

In [25]:
# Get multiple aggregate statistics for beer and wine servings for each continent
drinks_grouped[["beer_servings", "wine_servings"]].agg(["mean", "min", "max", "median"])

          beer_servings                 wine_servings
                   mean min  max median          mean min  max median
continent
AF            61.471698   0  376   32.0     16.264151   0  233    2.0
AS            37.045455   0  247   17.5      9.068182   0  123    1.0
EU           193.777778   0  361  219.0    142.222222   0  370  128.0
OC            89.687500   0  306   52.5     35.625000   0  212    8.5
SA           175.083333  93  333  162.5     62.416667   1  221   12.0
UNKNOWN      145.434783   1  285  143.0     24.521739   1  100   11.0

In [26]:
# Get multiple aggregate statistics for several columns for each continent
drinks_grouped.agg(
    {
        "beer_servings": ["min", "max"],
        "wine_servings": ["mean", "median"],
        "spirit_servings": ["mean", "median"]
    }
)

          beer_servings      wine_servings        spirit_servings
                    min  max          mean median            mean median
continent
AF                    0  376     16.264151    2.0       16.339623    3.0
AS                    0  247      9.068182    1.0       60.840909   16.0
EU                    0  361    142.222222  128.0      132.555556  122.0
OC                    0  306     35.625000    8.5       58.437500   37.0
SA                   93  333     62.416667   12.0      114.750000  108.5
UNKNOWN               1  285     24.521739   11.0      165.739130  137.0