# Apply

In [1]:
import pandas as pd

## Primer

In [2]:
df = pd.DataFrame(
    {
        "Name": ["John", "Rock", "Neil", "Tom"],
        "Group": [
            "A",
            "A",
            "B",
            "B",
        ],
        "Marks": [78, 66, 55, 42],
    }
)
display(df)

   Name Group  Marks
0  John     A     78
1  Rock     A     66
2  Neil     B     55
3   Tom     B     42

In [3]:
# Define a function to convert marks to percentage string
def make_percent(val):
    return str(val)+"%"


# Apply the function to create a new column "Marks (%)"
df["Marks (%)"] = df["Marks"].apply(make_percent)

In [4]:
display(df)

   Name Group  Marks Marks (%)
0  John     A     78       78%
1  Rock     A     66       66%
2  Neil     B     55       55%
3   Tom     B     42       42%

In [5]:
# Create a new column "Pass" which contains True if the student has passed the exam, False otherwise
# A student is considered to be passed if he/she has scored 70 or more marks in group A and 50 or more marks in group B.

# Define a function to determine if a student has passed
def is_pass(row):
    
    group = row["Group"]
    marks = row["Marks"]

    if group == "A":
        if marks >= 70:
            return True
        else:
            return False
    else:
        if marks >= 50:
            return True
        else:
            return False

# Apply the function to create the "Pass" column
df["Pass"] = df.apply(is_pass, axis=1)

display(df)

   Name Group  Marks Marks (%)   Pass
0  John     A     78       78%   True
1  Rock     A     66       66%  False
2  Neil     B     55       55%   True
3   Tom     B     42       42%  False

## Real Data

In [6]:
# Load the student performance dataset
df_raw = pd.read_csv("./data/student_mat.csv")

# Display the info of the raw dataframe
df_raw.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10

In [7]:
# Display the info of the raw dataframe
df_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 395 entries, 0 to 394
Data columns (total 33 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   school      395 non-null    object
 1   sex         395 non-null    object
 2   age         395 non-null    int64
 3   address     395 non-null    object
 4   famsize     395 non-null    object
 5   Pstatus     395 non-null    object
 6   Medu        395 non-null    int64
 7   Fedu        395 non-null    int64
 8   Mjob        395 non-null    object
 9   Fjob        395 non-null    object
 10  reason      395 non-null    object
 11  guardian    395 non-null    object
 12  traveltime  395 non-null    int64
 13  studytime   395 non-null    int64
 14  failures    395 non-null    int64
 15  schoolsup   395 non-null    object
 16  famsup      395 non-null    object
 17  paid        395 non-null    object
 18  activities  395 non-null    object
 19  nursery     395 non-null    object
 20  higher      395 non-null    object
 21  internet    395 non-null    object
 22  romantic    395 non-null    object
 23  famrel      395 non-null    int64
 24  freetime    395 non-null    int64
 25  goout       395 non-null    int64
 26  Dalc        395 non-null    int64
 27  Walc        395 non-null    int64
 28  health      395 non-null    int64
 29  absences    395 non-null    int64
 30  G1          395 non-null    int64
 31  G2          395 non-null    int64
 32  G3          395 non-null    int64
dtypes: int64(16), object(17)
memory usage: 102.0+ KB

In [8]:
display(df_raw.isnull().sum())
display(df_raw.duplicated().sum())

school        0
sex           0
age           0
address       0
famsize       0
Pstatus       0
Medu          0
Fedu          0
Mjob          0
Fjob          0
reason        0
guardian      0
traveltime    0
studytime     0
failures      0
schoolsup     0
famsup        0
paid          0
activities    0
nursery       0
higher        0
internet      0
romantic      0
famrel        0
freetime      0
goout         0
Dalc          0
Walc          0
health        0
absences      0
G1            0
G2            0
G3            0
dtype: int64

np.int64(0)

In [9]:
# For the purpose of this exercise slice the dataframe from 'school' until the 'guardian' column
df_stu = df_raw.loc[:, "school":"guardian"]
df_stu

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,guardian
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,course,mother
1,GP,F,17,U,GT3,T,1,1,at_home,other,course,father
2,GP,F,15,U,LE3,T,1,1,at_home,other,other,mother
3,GP,F,15,U,GT3,T,4,2,health,services,home,mother
4,GP,F,16,U,GT3,T,3,3,other,other,home,father
...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,20,U,LE3,A,2,2,services,services,course,other
391,MS,M,17,U,LE3,T,3,1,services,services,course,mother
392,MS,M,21,R,GT3,T,1,1,other,other,course,other
393,MS,M,18,R,LE3,T,3,2,services,other,course,mother
394,MS,M,19,U,LE3,T,1,1,other,at_home,course,father

In [10]:
# Create a function that will capitalize strings
def capitalizer(val):
    return str(val).upper()


# Apply the function to the 'Mjob' and 'Fjob' columns
df_stu["Mjob"] = df_stu["Mjob"].apply(capitalizer)
df_stu["Fjob"] = df_stu["Fjob"].apply(capitalizer)

In [11]:
display(df_stu)

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,guardian
0,GP,F,18,U,GT3,A,4,4,AT_HOME,TEACHER,course,mother
1,GP,F,17,U,GT3,T,1,1,AT_HOME,OTHER,course,father
2,GP,F,15,U,LE3,T,1,1,AT_HOME,OTHER,other,mother
3,GP,F,15,U,GT3,T,4,2,HEALTH,SERVICES,home,mother
4,GP,F,16,U,GT3,T,3,3,OTHER,OTHER,home,father
...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,20,U,LE3,A,2,2,SERVICES,SERVICES,course,other
391,MS,M,17,U,LE3,T,3,1,SERVICES,SERVICES,course,mother
392,MS,M,21,R,GT3,T,1,1,OTHER,OTHER,course,other
393,MS,M,18,R,LE3,T,3,2,SERVICES,OTHER,course,mother
394,MS,M,19,U,LE3,T,1,1,OTHER,AT_HOME,course,father

In [12]:
# Create a function that will return True if the age is greater than 17, else False
def is_legal_drinker(val):
    return val > 17


# Apply the function to create the "legal_drinker" column
df_stu["legal_drinker"] = df_stu["age"].apply(is_legal_drinker)

display(df_stu)

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,guardian,legal_drinker
0,GP,F,18,U,GT3,A,4,4,AT_HOME,TEACHER,course,mother,True
1,GP,F,17,U,GT3,T,1,1,AT_HOME,OTHER,course,father,False
2,GP,F,15,U,LE3,T,1,1,AT_HOME,OTHER,other,mother,False
3,GP,F,15,U,GT3,T,4,2,HEALTH,SERVICES,home,mother,False
4,GP,F,16,U,GT3,T,3,3,OTHER,OTHER,home,father,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,20,U,LE3,A,2,2,SERVICES,SERVICES,course,other,True
391,MS,M,17,U,LE3,T,3,1,SERVICES,SERVICES,course,mother,False
392,MS,M,21,R,GT3,T,1,1,OTHER,OTHER,course,other,True
393,MS,M,18,R,LE3,T,3,2,SERVICES,OTHER,course,mother,True
394,MS,M,19,U,LE3,T,1,1,OTHER,AT_HOME,course,father,True

In [13]:
# Create a function that categorizes students based on their age and sex
# If age < 18 and sex = 'F' => 'Underage Female'
# If age < 18 and sex = 'M' => 'Underage Male'
# If age >= 18 and sex = 'F' => 'Adult Female'
# If age >= 18 and sex = 'M' => 'Adult Male'
def categorize_by_age_and_sex(row):
    age = row["age"]
    sex = row["sex"]

    if (age < 18) and (sex == 'F'):
        return "Underage Female"
    elif (age < 18) and (sex == 'M'):
        return "Underage Male"
    elif (age > 18) and (sex == 'F'):
        return "Adult Female"
    else:
        return "Adult Male"


# Apply the function to create the "category" column
df_stu["category"] = df_stu.apply(categorize_by_age_and_sex, axis=1)

# Display the relevant columns
display(df_stu[["sex", "age", "category"]])

    sex  age         category
0     F   18       Adult Male
1     F   17  Underage Female
2     F   15  Underage Female
3     F   15  Underage Female
4     F   16  Underage Female
..   ..  ...              ...
390   M   20       Adult Male
391   M   17    Underage Male
392   M   21       Adult Male
393   M   18       Adult Male
394   M   19       Adult Male

[395 rows x 3 columns]

### Apply with groupby

In [14]:
# Group the dataframe by the new column "category"
df_stu_grouped = df_stu.groupby(by="category")

In [15]:
# Display the size of each group
df_stu_grouped.size()

category
Adult Female        15
Adult Male          96
Underage Female    150
Underage Male      134
dtype: int64

In [16]:
# Display the number of unique values in each group
df_stu_grouped.nunique()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,guardian,legal_drinker
category,,,,,,,,,,,,,
Adult Female,2,1,2,2,2,2,5,4,4,4,4,2,1
Adult Male,2,2,5,2,2,2,4,4,5,5,4,3,1
Underage Female,2,1,3,2,2,2,5,4,5,5,4,3,1
Underage Male,2,1,3,2,2,2,5,5,5,5,4,3,1

In [28]:
# Create a function that calculates the average age of students 
# whose father is a teacher vs those whose father is not a teacher
def average_age_of_teacher(df):
    filt_teacher = df["Fjob"] == "TEACHER"
    mean_age_teacher = df[filt_teacher]["age"].mean()
    mean_age_not_teacher = df[~filt_teacher]["age"].mean()
    return pd.Series(
        {
            "Mean Age Teacher": mean_age_teacher,
            "Mean Age Not Teacher": mean_age_not_teacher
        }
    )


# # # Testing the function on a single group
# group_list = list(df_stu_grouped.groups.keys())
# # print(group_list)

# df = df_stu_grouped.get_group(group_list[0])
# # display(df)

# filt_teacher = df["Fjob"] == "TEACHER"
# mean_age_teacher = df.loc[filt_teacher, "age"].mean()
# mean_age_not_techer = df.loc[~filt_teacher, "age"].mean()

# pd.Series(
#     {
#         "Mean Age Techer": mean_age_teacher, 
#         "Mean Age Not Teacher": mean_age_not_techer
#     }
# )

# Actually apply the function
df_stu_grouped.apply(average_age_of_teacher, include_groups=False)

                 Mean Age Teacher  Mean Age Not Teacher
category
Adult Female                  NaN             19.066667
Adult Male              18.000000             18.230769
Underage Female         16.181818             16.129496
Underage Male           15.923077             15.975207