# Merge

In [1]:
import pandas as pd

In [2]:
# Sample raw data dictionaries
raw_data_1 = {
    "subject_id": ["1", "2", "3", "4", "5"],
    "first_name": ["Alex", "Amy", "Allen", "Alice", "Ayoung"],
    "last_name": ["Anderson", "Ackerman", "Ali", "Aoni", "Atiches"],
}

raw_data_2 = {
    "subject_id": ["4", "5", "6", "7", "8"],
    "first_name": ["Billy", "Brian", "Bran", "Bryce", "Betty"],
    "last_name": ["Bonder", "Black", "Balwner", "Brice", "Btisan"],
}

raw_data_3 = {"subject_id": ["1", "2", "3", "4", "6"], "test_id": [11, 12, 13, 14, 16]}

In [3]:
# Create DataFrames from the raw data
data1 = pd.DataFrame(raw_data_1, columns=["subject_id", "first_name", "last_name"])
data2 = pd.DataFrame(raw_data_2, columns=["subject_id", "first_name", "last_name"])
data3 = pd.DataFrame(raw_data_3, columns=["subject_id", "test_id"])

display(data1)
display(data2)
display(data3)

  subject_id first_name last_name
0          1       Alex  Anderson
1          2        Amy  Ackerman
2          3      Allen       Ali
3          4      Alice      Aoni
4          5     Ayoung   Atiches

  subject_id first_name last_name
0          4      Billy    Bonder
1          5      Brian     Black
2          6       Bran   Balwner
3          7      Bryce     Brice
4          8      Betty    Btisan

  subject_id  test_id
0          1       11
1          2       12
2          3       13
3          4       14
4          6       16

In [5]:
# Save the DataFrames to an Excel file with separate sheets
names = ["data1", "data2", "data3"]
dataframes = [data1, data2, data3]
with pd.ExcelWriter("merge_raw.xlsx") as writer:
    for name, frame in zip(names, dataframes):
        frame.to_excel(writer, sheet_name=name, index=False)

In [ ]:
# Concatenate data1 and data2 vertically
all_data = pd.concat([data1, data2])
display(all_data)

  subject_id first_name last_name
0          1       Alex  Anderson
1          2        Amy  Ackerman
2          3      Allen       Ali
3          4      Alice      Aoni
4          5     Ayoung   Atiches
0          4      Billy    Bonder
1          5      Brian     Black
2          6       Bran   Balwner
3          7      Bryce     Brice
4          8      Betty    Btisan

In [10]:
# Reset index after concatenation
all_data = all_data.reset_index(drop=True)
display(all_data)

  subject_id first_name last_name
0          1       Alex  Anderson
1          2        Amy  Ackerman
2          3      Allen       Ali
3          4      Alice      Aoni
4          5     Ayoung   Atiches
5          4      Billy    Bonder
6          5      Brian     Black
7          6       Bran   Balwner
8          7      Bryce     Brice
9          8      Betty    Btisan

In [11]:
# Concatenate data1 and data2 horizontally
pd.concat([data1, data2], axis=1)

  subject_id first_name last_name subject_id first_name last_name
0          1       Alex  Anderson          4      Billy    Bonder
1          2        Amy  Ackerman          5      Brian     Black
2          3      Allen       Ali          6       Bran   Balwner
3          4      Alice      Aoni          7      Bryce     Brice
4          5     Ayoung   Atiches          8      Betty    Btisan

### Join diagram

[Link](https://data36.com/wp-content/uploads/2018/08/4-pandas-merge-inner-outer-left-right-768x579.png)

In [12]:
# Merge all_data and data3 along the subject_id value (inner join)
pd.merge(all_data, data3, on="subject_id", how="inner")

# Alternate syntax for merging data1 and data3

  subject_id first_name last_name  test_id
0          1       Alex  Anderson       11
1          2        Amy  Ackerman       12
2          3      Allen       Ali       13
3          4      Alice      Aoni       14
4          4      Billy    Bonder       14
5          6       Bran   Balwner       16

In [14]:
# Merge all_data and data3 along the subject_id value (left join)
pd.merge(all_data, data3, on="subject_id", how="left")

  subject_id first_name last_name  test_id
0          1       Alex  Anderson     11.0
1          2        Amy  Ackerman     12.0
2          3      Allen       Ali     13.0
3          4      Alice      Aoni     14.0
4          5     Ayoung   Atiches      NaN
5          4      Billy    Bonder     14.0
6          5      Brian     Black      NaN
7          6       Bran   Balwner     16.0
8          7      Bryce     Brice      NaN
9          8      Betty    Btisan      NaN

In [15]:
# Merge all_data and data3 along the subject_id value (right join)
pd.merge(all_data, data3, on="subject_id", how="right")

  subject_id first_name last_name  test_id
0          1       Alex  Anderson       11
1          2        Amy  Ackerman       12
2          3      Allen       Ali       13
3          4      Alice      Aoni       14
4          4      Billy    Bonder       14
5          6       Bran   Balwner       16

In [ ]:
# Merge all_data and data3 along the subject_id value (outer join)
pd.merge(all_data, data3, on="subject_id", how="outer")

  subject_id first_name last_name  test_id
0          1       Alex  Anderson     11.0
1          2        Amy  Ackerman     12.0
2          3      Allen       Ali     13.0
3          4      Alice      Aoni     14.0
4          4      Billy    Bonder     14.0
5          5     Ayoung   Atiches      NaN
6          5      Brian     Black      NaN
7          6       Bran   Balwner     16.0
8          7      Bryce     Brice      NaN
9          8      Betty    Btisan      NaN

In [17]:
# Change columns header of data1 and data3 so that they are not matched.
data1 = data1.rename(columns={"subject_id": "id1"})
data3 = data3.rename(columns={"subject_id": "id3"})

# Merge all_data and data3 along the subject_id value (innter join)
pd.merge(data1, data3, left_on="id1", right_on="id3", how="inner")

  id1 first_name last_name id3  test_id
0   1       Alex  Anderson   1       11
1   2        Amy  Ackerman   2       12
2   3      Allen       Ali   3       13
3   4      Alice      Aoni   4       14

### Join `dummy_data1` and `dummy_data2` and the merge with the `dummy_data3`

In [21]:
dummy_data1 = {
    "id": ["1", "2", "3", "4", "5"],
    "Feature1": ["A", "C", "E", "G", "I"],
    "Feature2": ["B", "D", "F", "H", "J"],
}

dummy_data2 = {
    "id": ["1", "2", "6", "7", "8"],
    "Feature1": ["K", "M", "O", "Q", "S"],
    "Feature2": ["L", "N", "P", "R", "T"],
}

dummy_data3 = {
    "id": ["1", "2", "3", "4", "5", "7", "8", "9", "10", "11"],
    "Feature3": [12, 13, 14, 15, 16, 17, 15, 12, 13, 23],
}

dummy_df1 = pd.DataFrame(dummy_data1, columns=["id", "Feature1", "Feature2"])
dummy_df2 = pd.DataFrame(dummy_data2, columns=["id", "Feature1", "Feature2"])
dummy_df3 = pd.DataFrame(dummy_data3, columns=["id", "Feature3"])
display(dummy_df1)
display(dummy_df2)
display(dummy_df3)

  id Feature1 Feature2
0  1        A        B
1  2        C        D
2  3        E        F
3  4        G        H
4  5        I        J

  id Feature1 Feature2
0  1        K        L
1  2        M        N
2  6        O        P
3  7        Q        R
4  8        S        T

   id  Feature3
0   1        12
1   2        13
2   3        14
3   4        15
4   5        16
5   7        17
6   8        15
7   9        12
8  10        13
9  11        23

In [24]:
dummy_df12 = pd.concat([dummy_df1, dummy_df2])
display(dummy_df12)

  id Feature1 Feature2
0  1        A        B
1  2        C        D
2  3        E        F
3  4        G        H
4  5        I        J
0  1        K        L
1  2        M        N
2  6        O        P
3  7        Q        R
4  8        S        T

In [26]:
dummy_df12 = dummy_df12.reset_index(drop=True)
display(dummy_df12)

  id Feature1 Feature2
0  1        A        B
1  2        C        D
2  3        E        F
3  4        G        H
4  5        I        J
5  1        K        L
6  2        M        N
7  6        O        P
8  7        Q        R
9  8        S        T

In [27]:
pd.merge(dummy_df12, dummy_df3, on="id", how="inner")

  id Feature1 Feature2  Feature3
0  1        A        B        12
1  2        C        D        13
2  3        E        F        14
3  4        G        H        15
4  5        I        J        16
5  1        K        L        12
6  2        M        N        13
7  7        Q        R        17
8  8        S        T        15

In [28]:
pd.merge(dummy_df12, dummy_df3, on="id", how="left")

  id Feature1 Feature2  Feature3
0  1        A        B      12.0
1  2        C        D      13.0
2  3        E        F      14.0
3  4        G        H      15.0
4  5        I        J      16.0
5  1        K        L      12.0
6  2        M        N      13.0
7  6        O        P       NaN
8  7        Q        R      17.0
9  8        S        T      15.0

In [29]:
pd.merge(dummy_df12, dummy_df3, on="id", how="right")

    id Feature1 Feature2  Feature3
0    1        A        B        12
1    1        K        L        12
2    2        C        D        13
3    2        M        N        13
4    3        E        F        14
5    4        G        H        15
6    5        I        J        16
7    7        Q        R        17
8    8        S        T        15
9    9      NaN      NaN        12
10  10      NaN      NaN        13
11  11      NaN      NaN        23

In [30]:
pd.merge(dummy_df12, dummy_df3, on="id", how="outer")

    id Feature1 Feature2  Feature3
0    1        A        B      12.0
1    1        K        L      12.0
2   10      NaN      NaN      13.0
3   11      NaN      NaN      23.0
4    2        C        D      13.0
5    2        M        N      13.0
6    3        E        F      14.0
7    4        G        H      15.0
8    5        I        J      16.0
9    6        O        P       NaN
10   7        Q        R      17.0
11   8        S        T      15.0
12   9      NaN      NaN      12.0