# Pandas

In [1]:
# Importing the pandas package

import pandas as pd

## DataFrames and Series

- DataFrames are similar to Excel sheet.
- Series are similar to a single column in an Excel sheet.

In [2]:
# Sample sales data

sales_data = {
    "apple": [3, 2, 0, 1], 
    "orange": [0, 3, 7, 2], 
    "banana": [1, 0, 2, 4]
}

customers = ["June", "Robert", "Lily", "David"]

In [3]:
# Create a DataFrame from the dictionary 'sales_data'

pd.DataFrame(sales_data)

   apple  orange  banana
0      3       0       1
1      2       3       0
2      0       7       2
3      1       2       4

In [4]:
# Create a DataFrame with custom row labels

sales = pd.DataFrame(data=sales_data, index=customers)
sales.name = "Customer"

display(sales)

        apple  orange  banana
June        3       0       1
Robert      2       3       0
Lily        0       7       2
David       1       2       4

In [5]:
# Create series for a single column

sales["apple"]

June      3
Robert    2
Lily      0
David     1
Name: apple, dtype: int64

## Importing and Exporting File

In [6]:
# If using Google Colab, uncomment these lines
# from google.colab import drive
# drive.mount('/content/drive')

In [7]:
# If using Google Colab, uncomment these lines
# import os
# os.chdir('/content/drive/MyDrive/Colab Notebooks') # Change to your working directory
# !ls  # List files in the current directory to verify path change

In [8]:
# Reading DataFrame from CSV

sales = pd.read_csv("sales_data.csv", index_col="Customers")
display(sales)

           apple  orange  banana
Customers
June           3       0       1
Robert         2       3       0
Lily           0       7       2
David          1       2       4

In [9]:
# Reading DataFrame from Excel

sales_excel = pd.read_excel("sales_data.xlsx", index_col="Customers")
display(sales_excel)

           apple  orange  banana
Customers
June           3       0       1
Robert         2       3       0
Lily           0       7       2
David          1       2       4

In [10]:
# Exporting DataFrame to CSV and Excel

sales_excel.to_csv("sales_data_exported.csv")

In [11]:
sales

           apple  orange  banana
Customers
June           3       0       1
Robert         2       3       0
Lily           0       7       2
David          1       2       4

## Slicing DataFrames and Series

Difference between loc and iloc

- .loc is used for label-based indexing, which means you have to specify the names of the rows and columns that you want to filter out.
- .iloc is used for positional indexing, which means you have to specify rows and columns by their integer position values (0-based index).

In [12]:
# Locating DataFrame by row/column labels using .loc

# Method 1: Single row

display(sales.loc["June"])
# Method 2: Slicing rows

display(sales.loc["June":"Robert"])
# Method 3: Selecting specific columns

display(sales.loc[:, "apple"])
# Method 4: Slicing both rows and columns

display(sales.loc["June":"Lily", "apple":"banana"])
# Methhod 5: Selecting specific rows and columns

display(sales.loc[["June", "David"], ["apple", "banana"]])

apple     3
orange    0
banana    1
Name: June, dtype: int64

           apple  orange  banana
Customers
June           3       0       1
Robert         2       3       0

Customers
June      3
Robert    2
Lily      0
David     1
Name: apple, dtype: int64

           apple  orange  banana
Customers
June           3       0       1
Robert         2       3       0
Lily           0       7       2

           apple  banana
Customers
June           3       1
David          1       4

In [13]:
# Slicing DataFrame by row/column positions using .iloc

# Method 1: Single row

display(sales.iloc[0, :])
# Method 2: Slicing rows

display(sales.iloc[0:3, :])
# Method 3: Selecting specific columns

display(sales.iloc[0:3, 1])
# Method 4: Slicing both rows and columns

display(sales.iloc[0:3, 0:2])
# Method 5: Selecting specific rows and columns

display(sales.iloc[[0, 3], [0, 2]])

apple     3
orange    0
banana    1
Name: June, dtype: int64

           apple  orange  banana
Customers
June           3       0       1
Robert         2       3       0
Lily           0       7       2

Customers
June      0
Robert    3
Lily      7
Name: orange, dtype: int64

           apple  orange
Customers
June           3       0
Robert         2       3
Lily           0       7

           apple  banana
Customers
June           3       1
David          1       4

In [14]:
# If you only need columns, you can use the column names directly

sales[["apple", "banana"]]

           apple  banana
Customers
June           3       1
Robert         2       0
Lily           0       2
David          1       4

In [15]:
# Slicing the Series by index labels by using .loc

display(sales.loc["June":"David", ["apple", "banana"]])

           apple  banana
Customers
June           3       1
Robert         2       0
Lily           0       2
David          1       4

In [16]:
# Slicing the Series by index positions by using .iloc

display(sales.iloc[0:4, [0, 2]])

           apple  banana
Customers
June           3       1
Robert         2       0
Lily           0       2
David          1       4

## IMDB Movie Dataset

In [17]:
movies = pd.read_csv("IMDB-Movie-Data.csv", index_col="Title")
display(movies)

# You can use this link too.
# url = 'https://raw.githubusercontent.com/im-data-68/lectures/refs/heads/main/src/T02_basic_python_part_2/exercises/IMDB-Movie-Data.csv'
# movies = pd.read_csv(url, index_col="Title")

,Rank,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
Title,,,,,,,,,,,
Guardians of the Galaxy,1,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
Prometheus,2,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
Split,3,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
Sing,4,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
Suicide Squad,5,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0
...,...,...,...,...,...,...,...,...,...,...,...
Secret in Their Eyes,996,"Crime,Drama,Mystery","A tight-knit team of rising investigators, alo...",Billy Ray,"Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...",2015,111,6.2,27585,NaN,45.0
Hostel: Part II,997,Horror,Three American college students studying abroa...,Eli Roth,"Lauren German, Heather Matarazzo, Bijou Philli...",2007,94,5.5,73152,17.54,46.0
Step Up 2: The Streets,998,"Drama,Music,Romance",Romantic sparks occur between two dance studen...,Jon M. Chu,"Robert Hoffman, Briana Evigan, Cassie Ventura,...",2008,98,6.2,70699,58.01,50.0
Search Party,999,"Adventure,Comedy",A pair of friends embark on a mission to reuni...,Scot Armstrong,"Adam Pally, T.J. Miller, Thomas Middleditch,Sh...",2014,93,5.6,4881,NaN,22.0
Nine Lives,1000,"Comedy,Family,Fantasy",A stuffy businessman finds himself trapped ins...,Barry Sonnenfeld,"Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...",2016,87,5.3,12435,19.64,11.0

In [18]:
# If using Google Colab, you can use this library for nice data viewing. Uncomment the following lines
# from google.colab import data_table
# data_table.enable_dataframe_formatter()
# movies

In [19]:
# Display the first 5 rows of the DataFrame

movies.head()

,Rank,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
Title,,,,,,,,,,,
Guardians of the Galaxy,1,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
Prometheus,2,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
Split,3,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
Sing,4,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
Suicide Squad,5,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0

In [20]:
# Display the last 5 rows of the DataFrame

movies.tail()

,Rank,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
Title,,,,,,,,,,,
Secret in Their Eyes,996,"Crime,Drama,Mystery","A tight-knit team of rising investigators, alo...",Billy Ray,"Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...",2015,111,6.2,27585,NaN,45.0
Hostel: Part II,997,Horror,Three American college students studying abroa...,Eli Roth,"Lauren German, Heather Matarazzo, Bijou Philli...",2007,94,5.5,73152,17.54,46.0
Step Up 2: The Streets,998,"Drama,Music,Romance",Romantic sparks occur between two dance studen...,Jon M. Chu,"Robert Hoffman, Briana Evigan, Cassie Ventura,...",2008,98,6.2,70699,58.01,50.0
Search Party,999,"Adventure,Comedy",A pair of friends embark on a mission to reuni...,Scot Armstrong,"Adam Pally, T.J. Miller, Thomas Middleditch,Sh...",2014,93,5.6,4881,NaN,22.0
Nine Lives,1000,"Comedy,Family,Fantasy",A stuffy businessman finds himself trapped ins...,Barry Sonnenfeld,"Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...",2016,87,5.3,12435,19.64,11.0

In [21]:
# Display DataFrame summary information

movies.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, Guardians of the Galaxy to Nine Lives
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Rank                1000 non-null   int64
 1   Genre               1000 non-null   object
 2   Description         1000 non-null   object
 3   Director            1000 non-null   object
 4   Actors              1000 non-null   object
 5   Year                1000 non-null   int64
 6   Runtime (Minutes)   1000 non-null   int64
 7   Rating              1000 non-null   float64
 8   Votes               1000 non-null   int64
 9   Revenue (Millions)  872 non-null    float64
 10  Metascore           936 non-null    float64
dtypes: float64(3), int64(4), object(4)
memory usage: 126.0+ KB

In [22]:
# Display the shape of the DataFrame

rows, cols = movies.shape
print(f"#Rows = {rows}, #Columns = {cols}")

#Rows = 1000, #Columns = 11

In [23]:
# Display the column names of the DataFrame

movies.columns

Index(['Rank', 'Genre', 'Description', 'Director', 'Actors', 'Year',
       'Runtime (Minutes)', 'Rating', 'Votes', 'Revenue (Millions)',
       'Metascore'],
      dtype='object')

In [24]:
# Renaming columns

movies.rename(
    columns={
        'Runtime (Minutes)': 'Runtime_Minutes',
        'Revenue (Millions)': 'Revenue_Millions'
        }
)

,Rank,Genre,Description,Director,Actors,Year,Runtime_Minutes,Rating,Votes,Revenue_Millions,Metascore
Title,,,,,,,,,,,
Guardians of the Galaxy,1,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
Prometheus,2,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
Split,3,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
Sing,4,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
Suicide Squad,5,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0
...,...,...,...,...,...,...,...,...,...,...,...
Secret in Their Eyes,996,"Crime,Drama,Mystery","A tight-knit team of rising investigators, alo...",Billy Ray,"Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...",2015,111,6.2,27585,NaN,45.0
Hostel: Part II,997,Horror,Three American college students studying abroa...,Eli Roth,"Lauren German, Heather Matarazzo, Bijou Philli...",2007,94,5.5,73152,17.54,46.0
Step Up 2: The Streets,998,"Drama,Music,Romance",Romantic sparks occur between two dance studen...,Jon M. Chu,"Robert Hoffman, Briana Evigan, Cassie Ventura,...",2008,98,6.2,70699,58.01,50.0
Search Party,999,"Adventure,Comedy",A pair of friends embark on a mission to reuni...,Scot Armstrong,"Adam Pally, T.J. Miller, Thomas Middleditch,Sh...",2014,93,5.6,4881,NaN,22.0
Nine Lives,1000,"Comedy,Family,Fantasy",A stuffy businessman finds himself trapped ins...,Barry Sonnenfeld,"Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...",2016,87,5.3,12435,19.64,11.0

In [25]:
# But those names weren't literally alternated in the actual dataframe
# unless we put 'inplace=True'.

movies.columns

Index(['Rank', 'Genre', 'Description', 'Director', 'Actors', 'Year',
       'Runtime (Minutes)', 'Rating', 'Votes', 'Revenue (Millions)',
       'Metascore'],
      dtype='object')

In [26]:
# You can set all column names at once
new_column_names = [
    "rank",
    "genre",
    "description",
    "director",
    "actors",
    "year",
    "runtime_minutes",
    "rating",
    "votes",
    "revenue_millions",
    "metascore",
]

In [27]:
# Better way to rename columns is to use a loop

c = movies.columns
cnew = []
for name in c:
    cnew.append(name.lower())

movies.columns = cnew
print(movies.columns)

Index(['rank', 'genre', 'description', 'director', 'actors', 'year',
       'runtime (minutes)', 'rating', 'votes', 'revenue (millions)',
       'metascore'],
      dtype='object')

In [28]:
# Another way using list comprehension
movies.columns = [col.lower() for col in movies]
print(movies.columns)

Index(['rank', 'genre', 'description', 'director', 'actors', 'year',
       'runtime (minutes)', 'rating', 'votes', 'revenue (millions)',
       'metascore'],
      dtype='object')

In [29]:
# Display basic statistical details like percentile, mean, std etc. of a DataFrame

movies.describe()

,rank,year,runtime (minutes),rating,votes,revenue (millions),metascore
count,1000.000000,1000.000000,1000.000000,1000.000000,1.000000e+03,872.000000,936.000000
mean,500.500000,2012.783000,113.172000,6.723200,1.698083e+05,82.956376,58.985043
std,288.819436,3.205962,18.810908,0.945429,1.887626e+05,103.253540,17.194757
min,1.000000,2006.000000,66.000000,1.900000,6.100000e+01,0.000000,11.000000
25%,250.750000,2010.000000,100.000000,6.200000,3.630900e+04,13.270000,47.000000
50%,500.500000,2014.000000,111.000000,6.800000,1.107990e+05,47.985000,59.500000
75%,750.250000,2016.000000,123.000000,7.400000,2.399098e+05,113.715000,72.000000
max,1000.000000,2016.000000,191.000000,9.000000,1.791916e+06,936.630000,100.000000

In [30]:
# Display basic statistical details of a specific column. This is Series.

display(movies["rank"].describe())
display(movies["genre"].describe())

count    1000.000000
mean      500.500000
std       288.819436
min         1.000000
25%       250.750000
50%       500.500000
75%       750.250000
max      1000.000000
Name: rank, dtype: float64

count                        1000
unique                        207
top       Action,Adventure,Sci-Fi
freq                           50
Name: genre, dtype: object

In [31]:
# Count the number of unique values in a specific column

display(movies["genre"].value_counts())
print("#Unique genres = ", movies["genre"].nunique())

genre
Action,Adventure,Sci-Fi     50
Drama                       48
Comedy,Drama,Romance        35
Comedy                      32
Drama,Romance               31
                            ..
Drama,Fantasy,Musical        1
Adventure,Family             1
Adventure,Comedy,Fantasy     1
Drama,Family,Music           1
Comedy,Family,Fantasy        1
Name: count, Length: 207, dtype: int64

#Unique genres =  207

In [32]:
display(movies["actors"].value_counts())
print("#Unique Actors = ", movies["actors"].nunique())

actors
Shia LaBeouf, Megan Fox, Josh Duhamel, Tyrese Gibson                       2
Gerard Butler, Aaron Eckhart, Morgan Freeman,Angela Bassett                2
Daniel Radcliffe, Emma Watson, Rupert Grint, Michael Gambon                2
Jennifer Lawrence, Josh Hutcherson, Liam Hemsworth, Woody Harrelson        2
James McAvoy, Anya Taylor-Joy, Haley Lu Richardson, Jessica Sula           1
                                                                          ..
Chiwetel Ejiofor, Nicole Kidman, Julia Roberts, Dean Norris                1
Lauren German, Heather Matarazzo, Bijou Phillips, Roger Bart               1
Robert Hoffman, Briana Evigan, Cassie Ventura, Adam G. Sevani              1
Adam Pally, T.J. Miller, Thomas Middleditch,Shannon Woodward               1
Noomi Rapace, Logan Marshall-Green, Michael Fassbender, Charlize Theron    1
Name: count, Length: 996, dtype: int64

#Unique Actors =  996

In [33]:
movies["genre"].value_counts().head(10)

genre
Action,Adventure,Sci-Fi       50
Drama                         48
Comedy,Drama,Romance          35
Comedy                        32
Drama,Romance                 31
Animation,Adventure,Comedy    27
Action,Adventure,Fantasy      27
Comedy,Drama                  27
Comedy,Romance                26
Crime,Drama,Thriller          24
Name: count, dtype: int64

In [34]:
# Inspect specific columns

movies[["genre", "rating"]]

                                            genre  rating
Title
Guardians of the Galaxy   Action,Adventure,Sci-Fi     8.1
Prometheus               Adventure,Mystery,Sci-Fi     7.0
Split                             Horror,Thriller     7.3
Sing                      Animation,Comedy,Family     7.2
Suicide Squad            Action,Adventure,Fantasy     6.2
...                                           ...     ...
Secret in Their Eyes          Crime,Drama,Mystery     6.2
Hostel: Part II                            Horror     5.5
Step Up 2: The Streets        Drama,Music,Romance     6.2
Search Party                     Adventure,Comedy     5.6
Nine Lives                  Comedy,Family,Fantasy     5.3

[1000 rows x 2 columns]

In [35]:
# Inspect specific row using .loc

movies.loc["Guardians of the Galaxy", :]

rank                                                                  1
genre                                           Action,Adventure,Sci-Fi
description           A group of intergalactic criminals are forced ...
director                                                     James Gunn
actors                Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...
year                                                               2014
runtime (minutes)                                                   121
rating                                                              8.1
votes                                                            757074
revenue (millions)                                               333.13
metascore                                                          76.0
Name: Guardians of the Galaxy, dtype: object

In [36]:
# Inspect specific row using .iloc

movies.iloc[-3:, :]

,rank,genre,description,director,actors,year,runtime (minutes),rating,votes,revenue (millions),metascore
Title,,,,,,,,,,,
Step Up 2: The Streets,998,"Drama,Music,Romance",Romantic sparks occur between two dance studen...,Jon M. Chu,"Robert Hoffman, Briana Evigan, Cassie Ventura,...",2008,98,6.2,70699,58.01,50.0
Search Party,999,"Adventure,Comedy",A pair of friends embark on a mission to reuni...,Scot Armstrong,"Adam Pally, T.J. Miller, Thomas Middleditch,Sh...",2014,93,5.6,4881,NaN,22.0
Nine Lives,1000,"Comedy,Family,Fantasy",A stuffy businessman finds himself trapped ins...,Barry Sonnenfeld,"Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...",2016,87,5.3,12435,19.64,11.0

In [37]:
# Filtering DataFrame using a condition

movies[movies["director"] == "Ridley Scott"][["rank", "genre", "director"]]

                        rank                     genre      director
Title
Prometheus                 2  Adventure,Mystery,Sci-Fi  Ridley Scott
The Martian              103    Adventure,Drama,Sci-Fi  Ridley Scott
Robin Hood               388    Action,Adventure,Drama  Ridley Scott
American Gangster        471     Biography,Crime,Drama  Ridley Scott
Exodus: Gods and Kings   517    Action,Adventure,Drama  Ridley Scott
The Counselor            522      Crime,Drama,Thriller  Ridley Scott
A Good Year              531      Comedy,Drama,Romance  Ridley Scott
Body of Lies             738      Action,Drama,Romance  Ridley Scott

In [38]:
# Filtering DataFrame using multiple conditions

filt_1 = movies["director"] == "Ridley Scott"
filt_2 = movies["rating"] >= 7.6

display(movies[filt_1 & filt_2])

,rank,genre,description,director,actors,year,runtime (minutes),rating,votes,revenue (millions),metascore
Title,,,,,,,,,,,
The Martian,103,"Adventure,Drama,Sci-Fi",An astronaut becomes stranded on Mars after hi...,Ridley Scott,"Matt Damon, Jessica Chastain, Kristen Wiig, Ka...",2015,144,8.0,556097,228.43,80.0
American Gangster,471,"Biography,Crime,Drama","In 1970s America, a detective works to bring d...",Ridley Scott,"Denzel Washington, Russell Crowe, Chiwetel Eji...",2007,157,7.8,337835,130.13,76.0

In [39]:
# Using .isin() for filtering based on multiple values

filt = movies["director"].isin(["Christopher Nolan", "Ridley Scott"])

movies[filt]

,rank,genre,description,director,actors,year,runtime (minutes),rating,votes,revenue (millions),metascore
Title,,,,,,,,,,,
Prometheus,2,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
Interstellar,37,"Adventure,Drama,Sci-Fi",A team of explorers travel through a wormhole ...,Christopher Nolan,"Matthew McConaughey, Anne Hathaway, Jessica Ch...",2014,169,8.6,1047747,187.99,74.0
The Dark Knight,55,"Action,Crime,Drama",When the menace known as the Joker wreaks havo...,Christopher Nolan,"Christian Bale, Heath Ledger, Aaron Eckhart,Mi...",2008,152,9.0,1791916,533.32,82.0
The Prestige,65,"Drama,Mystery,Sci-Fi",Two stage magicians engage in competitive one-...,Christopher Nolan,"Christian Bale, Hugh Jackman, Scarlett Johanss...",2006,130,8.5,913152,53.08,66.0
Inception,81,"Action,Adventure,Sci-Fi","A thief, who steals corporate secrets through ...",Christopher Nolan,"Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen...",2010,148,8.8,1583625,292.57,74.0
The Martian,103,"Adventure,Drama,Sci-Fi",An astronaut becomes stranded on Mars after hi...,Ridley Scott,"Matt Damon, Jessica Chastain, Kristen Wiig, Ka...",2015,144,8.0,556097,228.43,80.0
The Dark Knight Rises,125,"Action,Thriller",Eight years after the Joker's reign of anarchy...,Christopher Nolan,"Christian Bale, Tom Hardy, Anne Hathaway,Gary ...",2012,164,8.5,1222645,448.13,78.0
Robin Hood,388,"Action,Adventure,Drama","In 12th century England, Robin and his band of...",Ridley Scott,"Russell Crowe, Cate Blanchett, Matthew Macfady...",2010,140,6.7,221117,105.22,53.0
American Gangster,471,"Biography,Crime,Drama","In 1970s America, a detective works to bring d...",Ridley Scott,"Denzel Washington, Russell Crowe, Chiwetel Eji...",2007,157,7.8,337835,130.13,76.0
Exodus: Gods and Kings,517,"Action,Adventure,Drama",The defiant leader Moses rises up against the ...,Ridley Scott,"Christian Bale, Joel Edgerton, Ben Kingsley, S...",2014,150,6.0,137299,65.01,52.0
The Counselor,522,"Crime,Drama,Thriller",A lawyer finds himself in over his head when h...,Ridley Scott,"Michael Fassbender, Penélope Cruz, Cameron Dia...",2013,117,5.3,84927,16.97,48.0
A Good Year,531,"Comedy,Drama,Romance",A British investment broker inherits his uncle...,Ridley Scott,"Russell Crowe, Abbie Cornish, Albert Finney, M...",2006,117,6.9,74674,7.46,47.0
Body of Lies,738,"Action,Drama,Romance",A CIA agent on the ground in Jordan hunts down...,Ridley Scott,"Leonardo DiCaprio, Russell Crowe, Mark Strong,...",2008,128,7.1,182305,39.38,57.0

In [40]:
# Filtering movies released between 2005 and 2010 (inclusive) with a rating above 8.0 and revenue in the lowest 25th percentile

filt1 = movies["year"] >= 2005
filt2 = movies["year"] <= 2010
filt3 = movies["rating"] > 8.0
filt4 = movies["revenue (millions)"] < movies["revenue (millions)"].quantile(0.25)

movies[filt1 & filt2 & filt3 & filt4]

,rank,genre,description,director,actors,year,runtime (minutes),rating,votes,revenue (millions),metascore
Title,,,,,,,,,,,
3 Idiots,431,"Comedy,Drama",Two friends are searching for their long lost ...,Rajkumar Hirani,"Aamir Khan, Madhavan, Mona Singh, Sharman Joshi",2009,170,8.4,238789,6.52,67.0
The Lives of Others,477,"Drama,Thriller","In 1984 East Berlin, an agent of the secret po...",Florian Henckel von Donnersmarck,"Ulrich Mühe, Martina Gedeck,Sebastian Koch, Ul...",2006,137,8.5,278103,11.28,89.0
Incendies,714,"Drama,Mystery,War",Twins journey to the Middle East to discover t...,Denis Villeneuve,"Lubna Azabal, Mélissa Désormeaux-Poulin, Maxim...",2010,131,8.2,92863,6.86,80.0
Taare Zameen Par,992,"Drama,Family,Music",An eight-year-old boy is thought to be a lazy ...,Aamir Khan,"Darsheel Safary, Aamir Khan, Tanay Chheda, Sac...",2007,165,8.5,102697,1.20,42.0

In [41]:
# Create a new column name "rating_category" based on existing "rating" column

def get_rating_category(rate):

    if rate > 8.0:
        return "Good"
    return "Bad"

# movies["rating_category"] = movies["rating"].apply(get_rating_category)

In [42]:
# Shorter way using lambda function

movies["rating_category"] = movies["rating"].apply(
    lambda x: "good" if x >= 8.0 else "bad"
)

In [43]:
movies["rating_category"].value_counts()

rating_category
bad     922
good     78
Name: count, dtype: int64

In [44]:
movies.shape

(1000, 12)

In [45]:
display(movies)

,rank,genre,description,director,actors,year,runtime (minutes),rating,votes,revenue (millions),metascore,rating_category
Title,,,,,,,,,,,,
Guardians of the Galaxy,1,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0,good
Prometheus,2,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0,bad
Split,3,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0,bad
Sing,4,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0,bad
Suicide Squad,5,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0,bad
...,...,...,...,...,...,...,...,...,...,...,...,...
Secret in Their Eyes,996,"Crime,Drama,Mystery","A tight-knit team of rising investigators, alo...",Billy Ray,"Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...",2015,111,6.2,27585,NaN,45.0,bad
Hostel: Part II,997,Horror,Three American college students studying abroa...,Eli Roth,"Lauren German, Heather Matarazzo, Bijou Philli...",2007,94,5.5,73152,17.54,46.0,bad
Step Up 2: The Streets,998,"Drama,Music,Romance",Romantic sparks occur between two dance studen...,Jon M. Chu,"Robert Hoffman, Briana Evigan, Cassie Ventura,...",2008,98,6.2,70699,58.01,50.0,bad
Search Party,999,"Adventure,Comedy",A pair of friends embark on a mission to reuni...,Scot Armstrong,"Adam Pally, T.J. Miller, Thomas Middleditch,Sh...",2014,93,5.6,4881,NaN,22.0,bad
Nine Lives,1000,"Comedy,Family,Fantasy",A stuffy businessman finds himself trapped ins...,Barry Sonnenfeld,"Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...",2016,87,5.3,12435,19.64,11.0,bad